#!/bin/bash
# Directory name of page artifacts generated by packages
PACKAGE_PAGE_DIR_NAME=github-page
GITHUB_PAGE_ROOT=docs

DIRECTORIES=$(find . -type d -name $PACKAGE_PAGE_DIR_NAME)

# Copy page artifacts of packages to root page folder
for directory in $DIRECTORIES
do
  PARENT_BASENAME=$(basename $(dirname $directory));
  PAGE_PATH=$GITHUB_PAGE_ROOT/$PARENT_BASENAME;
  mkdir -p $PAGE_PATH;
  cp $directory/* $PAGE_PATH;
done

# Create HTML anchor tags for each package's page
PAGE_NAMES=$(for directory in $DIRECTORIES;
do
    PARENT_BASENAME=$(basename $(dirname $directory));
    echo "<li><a href=${PARENT_BASENAME}>${PARENT_BASENAME}</a></li>";
done );

# Create root HTML file for GitHub Pages
mkdir -p docs
cat > docs/index.html << EOF
<!DOCTYPE html>
<html>
  <head>
    <title>Packages preview</title>
  </head>
  <body>
    <ul>
    $PAGE_NAMES
    </ul>
  </body>
</html>
EOF

